#ifndef PROTOCOL_STATUS_H
#define PROTOCOL_STATUS_H

typedef enum
{
    PROTOCOL_OK = 0,
    PROTOCOL_NULL_ARGUMENT,
    PROTOCOL_BUFFER_TOO_SMALL,
    PROTOCOL_LENGTH_ERROR,
    PROTOCOL_ADDRESS_ERROR,
    PROTOCOL_FUNCTION_ERROR,
    PROTOCOL_CRC_ERROR,
    PROTOCOL_VERSION_ERROR,
    PROTOCOL_SUBFUNCTION_ERROR,
    PROTOCOL_STATUS_CODE_ERROR,
    PROTOCOL_FLAGS_ERROR,
    PROTOCOL_PAYLOAD_TOO_LARGE,
    PROTOCOL_PAYLOAD_LENGTH_MISMATCH,
    PROTOCOL_ALIGNMENT_ERROR,
    PROTOCOL_RANGE_ERROR
} protocol_status_t;

#endif /* PROTOCOL_STATUS_H */
