#ifndef GATEWAY_CONFIG_H
#define GATEWAY_CONFIG_H

#include <stdint.h>

#include "sdkconfig.h"

#define GATEWAY_EXPECTED_FLASH_SIZE_BYTES  (16UL * 1024UL * 1024UL)
#define GATEWAY_EXPECTED_PSRAM_SIZE_BYTES  (8UL * 1024UL * 1024UL)

#define GATEWAY_STM32_PRODUCT_ID            0x0001U
#define GATEWAY_STM32_HARDWARE_ID           0x0001U
#define GATEWAY_STM32_NODE_ADDRESS          1U
#define GATEWAY_STM32_APP_MAX_SIZE          0x000E0000UL

#define GATEWAY_FIRMWARE_PACKAGE_MAGIC      0x31465747UL
#define GATEWAY_FIRMWARE_PACKAGE_FORMAT     1U
#define GATEWAY_FIRMWARE_HEADER_SIZE        128U
#define GATEWAY_FIRMWARE_IMAGE_OFFSET       0x00001000UL
#define GATEWAY_FIRMWARE_VALID_MARKER       0xA5C3F00DUL
#define GATEWAY_FIRMWARE_SHA256_SIZE        32U
#define GATEWAY_FIRMWARE_DOWNLOAD_CHUNK_SIZE       4096U
#define GATEWAY_FIRMWARE_DOWNLOAD_CHECKPOINT_SIZE (64U * 1024U)
#define GATEWAY_FIRMWARE_DOWNLOAD_TASK_STACK_SIZE 10240U
#define GATEWAY_FIRMWARE_DOWNLOAD_TASK_PRIORITY    5U
#define GATEWAY_FIRMWARE_DOWNLOAD_ID_MAX_LENGTH    64U
#define GATEWAY_FIRMWARE_DOWNLOAD_ETAG_MAX_LENGTH  96U
#define GATEWAY_FIRMWARE_SERVER_URL_MAX_LENGTH     160U
#define GATEWAY_FIRMWARE_HTTP_TIMEOUT_MS           CONFIG_GATEWAY_FIRMWARE_HTTP_TIMEOUT_MS
#define GATEWAY_WIFI_CONNECT_TIMEOUT_MS            CONFIG_GATEWAY_WIFI_CONNECT_TIMEOUT_MS

#define GATEWAY_UPGRADE_UART_BAUD_RATE      115200U
#define GATEWAY_UPGRADE_UART_RX_BUFFER_SIZE 512U
#define GATEWAY_UPGRADE_UART_TX_TIMEOUT_MS  1000U

#define GATEWAY_NORMAL_REQUEST_TIMEOUT_MS   1000U
#define GATEWAY_DISCOVERY_TIMEOUT_MS        10000U
#define GATEWAY_ACTIVATE_APP_SILENCE_MS     1000U
#define GATEWAY_ERASE_TOTAL_TIMEOUT_MS      60000U
#define GATEWAY_ERASE_POLL_INTERVAL_MS      100U
#define GATEWAY_MAX_RETRY_COUNT             5U
#define GATEWAY_INVALID_RESPONSE_RETRY_DELAY_MS 250U
#define GATEWAY_STM32_CHECKPOINT_SIZE       4096U

#define GATEWAY_DISCOVERY_REQUEST_TIMEOUT_MS 100U
#define GATEWAY_TRANSFER_TASK_STACK_SIZE     8192U
#define GATEWAY_TRANSFER_TASK_PRIORITY       5U

#define GATEWAY_UPGRADE_CAP_BOOTLOADER       0x0001U
#define GATEWAY_UPGRADE_CAP_ENTER_BOOT       0x0002U
#define GATEWAY_UPGRADE_CAP_RESUME           0x0004U
#define GATEWAY_UPGRADE_CAP_CRC32            0x0008U

#define GATEWAY_STM32_BOOT_STATE_EMPTY            0U
#define GATEWAY_STM32_BOOT_STATE_APP_VALID        1U
#define GATEWAY_STM32_BOOT_STATE_UPDATE_REQUESTED 2U
#define GATEWAY_STM32_BOOT_STATE_ERASING          3U
#define GATEWAY_STM32_BOOT_STATE_RECEIVING        4U
#define GATEWAY_STM32_BOOT_STATE_VERIFYING        5U
#define GATEWAY_STM32_BOOT_STATE_PENDING_BOOT     6U
#define GATEWAY_STM32_BOOT_STATE_CONFIRMED        7U
#define GATEWAY_STM32_BOOT_STATE_FAILED           8U

#endif /* GATEWAY_CONFIG_H */
